name: Lint GitHub Actions

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review